version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'this is the dev branch'

      - run:
          name: install hasura CLI
          command: |
            curl -L https://github.com/hasura/graphql-engine/raw/stable/cli/get.sh | bash

      - run:
          name: test hasura CLI
          command: |
            hasura version


      - add_ssh_keys

      - checkout

      - run:
          command: | 
            #echo "known hosts before scan:"
            #cat ~/.ssh/known_hosts
            #ssh -o "StrictHostKeyChecking no" circleci@164.90.160.246 "echo hello world" 
            #echo "known hosts:"
            #cat ~/.ssh/known_hosts
            #echo "keyscan:"
            #ssh-keyscan -H -t rsa 164.90.160.246 >> tmp

            # get fingerprint
            #ssh-keygen -l -E sha256 -f tmp

            echo "${STAGING_HOST_PUB_KEY}" >> ~/.ssh/known_hosts


      - run:
          command: |
            echo "try to connect"
            ssh -v circleci@164.90.160.246 "echo hello world" 



      - run:
          name: test ssh
          command: |
            #ls ~/.ssh
            #cat ~/.ssh/config

            #echo "run keyscan"
            #ssh-keyscan 164.90.160.246 >> ~/.ssh/known_hosts
            #cat ~/.ssh/known_hosts

            echo "try to connect"
            ssh -v -o "StrictHostKeyChecking no" circleci@164.90.160.246 "echo hello world" 

            ssh circleci@164.90.160.246 "docker ps"

            cat ~/.ssh/known_hosts

            echo "execute local script remotely"

            ssh circleci@164.90.160.246 "sh -s" -- < script.sh "input"
            
      - run:
          name: test scp
          command: |
            scp script.sh circleci@164.90.160.246:~/script.sh



