version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
            echo 'this is the dev branch'

      - add_ssh_keys
        
      - run:
          command: |
            ssh-keyscan 164.90.160.246 >> ~/.ssh/known_hosts

      - run:
          name: test ssh
          command: |
            ssh -v root@164.90.160.246 "echo hello world" 


